app/routes.py
from flask import Blueprint, render_template, request, redirect, url_for
from app.models import Domains, WhoisService, DomainExpiration
from app import db
import json
bp = Blueprint('main', __name__)
from datetime import datetime
import pytz

@bp.route('/', methods=['GET', 'POST'])
def index():
    sweden_timezone = pytz.timezone('Europe/Stockholm')
    current_date = datetime.now(sweden_timezone)
    already_exists = False
    if request.method == 'POST':
        name = request.form.get('name')
        
        de = DomainExpiration()
        if '.' in name:
            domain, tld = de.extract_domain_and_tld(name)
            domain = domain.capitalize()
        else:
            already_exists = True
            domains = Domains.query.all()
            return render_template('index.html', domains=domains, already_exists=already_exists)
        name = f"{domain}.{tld}"
        existing_domain = Domains.query.filter_by(name=name).first()
        if existing_domain or tld == None:
            already_exists = True
            domains = Domains.query.all()
            return render_template('index.html', domains=domains, already_exists=already_exists)
        
        # Get Who is information
        whois_service = WhoisService()
        response = whois_service.query_domain(name)
        # Create a new domain
        result2 = response['response1']['result']
        available = response['response2']['result']
        registrar = "" if result2 == 'not found' else result2.get('registrar')
        creation_date = "" if result2 == 'not found' else result2.get('creation_date')
        updated_date = "" if result2 == 'not found' or result2.get('updated_date') == None else result2.get('updated_date')
        transfer_date = "" if result2 == 'not found' or  result2.get('transfer_date') == None else result2.get('transfer_date')
        expiration_date = "" if result2 == 'not found' else result2.get('expiration_date')
        name_servers = "" if result2 == 'not found' else result2.get('name_servers')
        last_updated = str(current_date)
        
        new_domain = Domains(name=name, available=available, registrar=registrar, creation_date=creation_date[:10], updated_date=updated_date[:10], transfer_date=transfer_date[:10], expiration_date=expiration_date[:10], name_servers=name_servers, last_updated=last_updated[:19])
        db.session.add(new_domain)
        db.session.commit()
        
        return redirect(url_for('main.index'))

    # Get all domains from the database
    domains = Domains.query.all()
    return render_template('index.html', domains=domains, already_exists=already_exists)
@bp.route('/remove_domain/<int:domain_id>', methods=['POST'])
def remove_domain(domain_id):
    domain = Domains.query.get_or_404(domain_id)
    db.session.delete(domain)
    db.session.commit()

    return redirect(url_for('main.index'))

@bp.route('/update_domain/<int:domain_id>', methods=['POST'])
def update_domain(domain_id):
    sweden_timezone = pytz.timezone('Europe/Stockholm')
    current_date = datetime.now(sweden_timezone)
    domain = Domains.query.filter_by(id=domain_id).first()
    whois_service = WhoisService()
    response = whois_service.query_domain(domain.name)
    # Create or update the domain
    print(response)
    result2 = response['response1']['result']
    available = response['response2']['result']
    registrar = "" if result2 == 'not found' else result2.get('registrar')
    creation_date = "" if result2 == 'not found' else result2.get('creation_date')
    updated_date = "" if result2 == 'not found' or result2.get('updated_date') is None else result2.get('updated_date')
    transfer_date = "" if result2 == 'not found' or result2.get('transfer_date') is None else result2.get('transfer_date')
    expiration_date = "" if result2 == 'not found' else result2.get('expiration_date')
    name_servers = "" if result2 == 'not found' else result2.get('name_servers')
    if name_servers  != "": 
        name_servers = ' '.join(name_servers)
    else:
        name_servers = ""
    last_updated = str(current_date)
    if domain:
    # Update the existing domain
        domain.available = available
        domain.registrar = registrar
        domain.creation_date = creation_date[:10]
        domain.updated_date = updated_date[:10]
        domain.transfer_date = transfer_date[:10]
        domain.expiration_date = expiration_date[:10]
        domain.name_servers = name_servers
        domain.last_updated = last_updated[:19]
    db.session.commit()
    return redirect(url_for('main.index'))

app/templates/index.html
<!DOCTYPE html>
<html>

<head>
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='styles.css') }}" />
    <title>StarWatch</title>
    <script>
        function scrollToDomain(id) {
            var domainNameElement = document.getElementById(id);
            domainNameElement.scrollIntoView({ behavior: 'smooth' });
        }
        function scrollToNextDomain(id) {
            var currentDomain = document.getElementById(id);
            var nextDomain = currentDomain.closest("li").nextElementSibling;
            console.log('Current domain: ', currentDomain);
            console.log('Next domain: ', nextDomain);
            if (nextDomain !== null) {
                nextDomain.querySelector(".posts").scrollIntoView({ behavior: 'smooth' });
                currentDomain.classList.remove("active-domain");
                nextDomain.querySelector(".posts").classList.add("active-domain");
            }
        }
        function menu(value) {
            var wrapper_menu = document.getElementById("wrapper-menu");
            var icon_container_menu = document.getElementById("add-domain-container-menu");
            var add_domain = document.getElementById("add-domain-container");
            console.log("add-domain", add_domain);
            if (value) {
                add_domain.style.display = "block";
            } else {
                add_domain.style.display = "none";
            }
        }   
    </script>
</head>

<body>
    <div id="wrapper">
        <div id="wrapper-menu">
            <img src="{{ url_for('static', filename='menu.svg') }}" onclick="menu(true)" />
        </div>
        <header>
            <div id="icon-container">

                <img src="{{ url_for('static', filename='starship.png')}}" />
                <div id="name">StarWatch</div>
                <div id="slogan">Domain Insight. Stellar Results.</div>
                <div class="arrow-down" onclick="scrollToDomain('section')">
                    <div>
                        &lt;
                    </div>
                </div>
                <div id="add-domain-container">
                    <div id="add-domain-container-menu">
                        <img src="{{ url_for('static', filename='menu_black.svg') }}" onclick="menu()" />
                    </div>
                    <form id="form-domain-name" method="POST" action="{{ url_for('main.index') }}">
                        <h1>Add domain</h1>
                        <input placeholder="Domain" type="text" name="name" id="add-domain-name"
                            class="add-domain-name{% if already_exists %} existing_name{% endif %}" required>
                        <input type="submit" value="Create">
                    </form>
                </div>
        </header>
        <section id="section">
            <ul>
                {% for domain in domains[::-1] %}
                <li>
                    <div class="posts{% if loop.first %} active-domain{% endif %}" id="{{domain.name}}">
                        <div class="posts-content">
                            {% if domain.registrar %}
                            <!-- Domain details for existing domains -->
                            <p><label class="subjects">Name:</label> <a href="https://{{domain.name}}">{{ domain.name
                                    }}</a>
                            </p>
                            <p><label class="subjects">Available:</label> <label class="registrar-available">{{
                                    domain.available
                                    }}</label></p>
                            <p><label class="subjects">Registrar:</label> {{ domain.registrar }}</p>
                            <p><label class="subjects">Creation date:</label> {{ domain.creation_date }}</p>
                            <p><label class="subjects">Updated date:</label> {{ domain.updated_date }}</p>
                            <p><label class="subjects">Transfer date:</label> {{ domain.transfer_date }}</p>
                            <p><label class="subjects">Expiration date:</label> {{domain.expiration_date}}</p>
                            <p><label class="subjects">Name servers:</label> {{domain.name_servers}}</p>
                            <p><label class="subjects">Last api update:</label> {{domain.last_updated}}</p>
                            <div class="forms">
                                <form class="update" method="POST"
                                    action="{{ url_for('main.update_domain', domain_id=domain.id) }}">
                                    <input type="submit" value="Update">
                                </form>
                                <form class="remove" method="POST"
                                    action="{{ url_for('main.remove_domain', domain_id=domain.id) }}">
                                    <input type="submit" value="Remove">
                                </form>
                                {% if loop.last %}
                                <div class="arrow-down arrow-up" onclick="scrollToDomain('wrapper')">
                                    <div>
                                        &lt;
                                    </div>
                                </div>
                                {% else %}
                                <div class="arrow-down" onclick="scrollToNextDomain(
                                    '{{domain.name}}'
                                )">
                                    <div>
                                        &lt;
                                    </div>
                                </div>
                                {% endif %}
                            </div>
                            {% else %}
                            <p><label class="subjects">Name:</label> <a href="https://{{domain.name}}">{{
                                    domain.name
                                    }}</a>
                            </p>
                            <p><label class="subjects">Available:</label> <label class="available">{{
                                    domain.available
                                    }}</label></p>
                            <p><label class="subjects">Last api update:</label> {{domain.last_updated}}</p>
                            <div class="forms">
                                <form class="update" method="POST"
                                    action="{{ url_for('main.update_domain', domain_id=domain.id) }}">
                                    <input type="submit" value="Update">
                                </form>
                                <form class="remove" method="POST"
                                    action="{{ url_for('main.remove_domain', domain_id=domain.id) }}">
                                    <input type="submit" value="Remove">
                                </form>
                                {% if loop.last %}
                                <div class="arrow-down arrow-up" onclick="scrollToDomain('wrapper')">
                                    <div>
                                        &lt;
                                    </div>
                                </div>
                                {% else %}
                                <div class="arrow-down" onclick="scrollToNextDomain('{{domain.name}}')">
                                    <div>
                                        &lt;
                                    </div>
                                </div>
                                {% endif %}
                            </div>
                            {% endif %}
                        </div>
                    </div>
                </li>
                {% endfor %}
            </ul>
        </section>
    </div>
</body>

</html>